### ISSUE TITLE
Images not displaying

### ISSUE THREAD

**Issue by adam-lab** [theatl-social/mastodon#10]
### Steps to reproduce the problem

1. In 'post' window, click the 'attachment' icon.
2. Select picture (this one:  ![DecaturStreets](https://github.com/theatl-social/mastodon/assets/1182021/0b4d0ab8-f8f6-42fe-a1c2-108eb58d3922)
3. Write text, write alt-text.
4. post.
5. Picture does not display.

[Example](https://beta.theatl.social/@decaturnature/112703112071148557).

![image](https://github.com/theatl-social/mastodon/assets/1182021/a7f8b04f-fc1c-4417-a3b5-5e5b88eb4364)

### Expected behaviour

display image

### Actual behaviour

no image displayed

### Mastodon instance

beta.theatl.social, default web interface.

### Mastodon version

beta

### Browser name and version

Firefox 126.0.1

### Operating system

Windows 11

**Comment by mikehikes** [comment]
Thank you! The underlying issue that caused the image to not be displayed has been resolved. I uploaded a new image and I was able to view. @adam-lab - if you wouldn't mind double-checking that you can upload, I would be appreciative (before I close out the ticket)!

**Comment by adam-lab** [comment]
I'm still not seeing them. I posted a few messages with images. One was copy/paste from clipboard, the other was download and attach. Neither seem to work. I was using the advanced web interface, and also tried copy/paste from regular interface.

**Comment by adam-lab** [comment]
this is working well. Thanks.
